FROM debian:jessie
MAINTAINER Emanuele Fornara "efornara@users.sourceforge.net"
RUN apt-get update
RUN apt-get install -y nano nvi make zip
RUN apt-get install -y python
RUN apt-get install -y ruby-ronn
RUN apt-get install -y g++
