FROM busybox
MAINTAINER Emanuele Fornara "efornara@users.sourceforge.net"
RUN wget http://downloads.sourceforge.net/project/jbit/jbit/v2.0.3/jbit-android-x86-static.bin -O /bin/jbit  ; chmod 755 /bin/jbit
