/*** File generated by inc2h.pl - DO NOT EDIT ***/

/*                                                                         */
/*  primo.inc                                                              */
/*                                                                         */

/*                                                                         */
/*  Copyright (C) 2014  Emanuele Fornara                                   */
/*  All rights reserved.                                                   */
/*                                                                         */
/*  Redistribution and use in source and binary forms, with or without     */
/*  modification, are permitted provided that the following conditions     */
/*  are met:                                                               */
/*   * Redistributions of source code must retain the above copyright      */
/*     notice, this list of conditions and the following disclaimer.       */
/*   * Redistributions in binary form must reproduce the above copyright   */
/*     notice, this list of conditions and the following disclaimer in     */
/*     the documentation and/or other materials provided with the          */
/*     distribution.                                                       */
/*                                                                         */
/*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS    */
/*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT      */
/*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS      */
/*  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE         */
/*  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,    */
/*  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,   */
/*  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS  */
/*  OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED     */
/*  AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, */
/*  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT     */
/*  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF     */
/*  SUCH DAMAGE.                                                           */
/*                                                                         */

#define REQPUT 0x0201
#define REQEND 0x0202
#define REQRES 0x0203

#define REQPTRLO 0x0204
#define REQPTRHI 0x0205

/*  4 bytes only                                                           */
#define REQDAT 0x0260

#define REQ_DELAY 1
#define REQ_MILLIS 2

#define IOBIT0 0x02F0
#define IOBIT1 0x02F1
#define IOBIT2 0x02F2
#define IOBIT3 0x02F3
#define IOBIT4 0x02F4
#define IOBIT5 0x02F5
#define IOBIT6 0x02F6
#define IOBIT7 0x02F7
#define IOBYTE 0x02F8
#define IOID 0x02F9

#define DIGID 0x02FA
#define DIGVAL 0x02FB
#define DIGWCFG 0x02FC
#define DIGPWM 0x02FD
#define ANLGLO 0x02FE
#define ANLGHI 0x02FF

#define DIGWCFG_INPUT 0
#define DIGWCFG_OUTPUT 1
#define DIGWCFG_INPULLUP 2

#define DIGVAL_HIGH 1
#define DIGVAL_LOW 0
