/*** File generated by inc2h.pl - DO NOT EDIT ***/

/*                                                                         */
/*  jbfmt.inc                                                              */
/*                                                                         */

/*                                                                         */
/*  Copyright (C) 2012-2017  Emanuele Fornara                              */
/*  All rights reserved.                                                   */
/*                                                                         */
/*  Redistribution and use in source and binary forms, with or without     */
/*  modification, are permitted provided that the following conditions     */
/*  are met:                                                               */
/*   * Redistributions of source code must retain the above copyright      */
/*     notice, this list of conditions and the following disclaimer.       */
/*   * Redistributions in binary form must reproduce the above copyright   */
/*     notice, this list of conditions and the following disclaimer in     */
/*     the documentation and/or other materials provided with the          */
/*     distribution.                                                       */
/*                                                                         */
/*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS    */
/*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT      */
/*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS      */
/*  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE         */
/*  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,    */
/*  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,   */
/*  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS  */
/*  OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED     */
/*  AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, */
/*  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT     */
/*  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF     */
/*  SUCH DAMAGE.                                                           */
/*                                                                         */

#define JBFMT_SIZE_HEADER 0x0C

#define JBFMT_OFFSET_SIGNATURE 0x00
#define JBFMT_OFFSET_HEADERLENGTH 0x04
#define JBFMT_OFFSET_VERSION 0x06
#define JBFMT_OFFSET_CODEPAGES 0x08
#define JBFMT_OFFSET_DATAPAGES 0x09
#define JBFMT_OFFSET_DEVID 0x0A

#define JBFMT_SIGNATURE_0 0x4A
#define JBFMT_SIGNATURE_1 0x42
#define JBFMT_SIGNATURE_2 0x69
#define JBFMT_SIGNATURE_3 0x74

#define JBFMT_VERSION_0_MAJOR 0x01
#define JBFMT_VERSION_1_MINOR 0x00

#define JBFMT_DEVID_UNSPEC 0x00
#define JBFMT_DEVID_STDOUT 0x01
#define JBFMT_DEVID_XV65 0x02
#define JBFMT_DEVID_MICROIO 0x03
#define JBFMT_DEVID_IO2 0x04
