#! /usr/bin/perl

$BSD = <<'END';
# BSD DEFAULTS
#

IS_JBIT = 1

.ifdef TARGET
.if $(TARGET) == "io2sim"
IS_JBIT = 0
.endif
.endif

.if $(IS_JBIT) == 1
OBJS = $(JBIT_OBJS) stdout.o xv65.o
OUT = jbit
.else
OBJS = $(IO2SIM_OBJS)
CXXFLAGS += -fPIC
LDFLAGS += -shared
OUT = io2sim.so
.endif

#
END

print <<END;
# File generated by genbsd.pl - DO NOT EDIT

END
$out = 1;
while (<>) {
	chop;
	if (/^# TARGET \/ PLATFORM DEFAULT$/) { $out = 0; print $BSD; }
	elsif (/^# LOCAL OVERRIDE/) { $out = 1; }
	if ($out) { print "$_\n"; }
}
