#! /usr/bin/python3

import zlib
import os

roms = [
	'vga14.rom',
]

directory = []

def chunker(seq, size):
	return (seq[pos:pos + size] for pos in range(0, len(seq), size))

print("""/*** File generated by genrom.py - DO NOT EDIT ***/

#include "rom.h"
""")

for file_name in roms:
	with open(file_name, "rb") as f:
		original_data = f.read()
		compressed_data = zlib.compress(original_data, 9)
		basename = os.path.basename(file_name)
		name, ext = os.path.splitext(basename)
		print('static const unsigned char %s_data[] = {' % name)
		for chunk in chunker(compressed_data, 16):
			print('\t', end='')
			for byte in chunk:
				print(str(byte), end=',')
			print()
		print('};\n')
		directory.append((basename, name,
			len(compressed_data), len(original_data)))

print('RomEntry rom_entries[] = {')
for entry in directory:
	print('\t{ "%s", %s_data, %d, %d },' % entry)
print('};')
print("RomResource rom_resources[%d];" % len(roms))
print("int n_of_roms = %d;" % len(roms))
