#! /usr/bin/perl

print <<END;
/*** File generated by inc2h.pl - DO NOT EDIT ***/

END
$pre = "";
while (<>) {
	chop;
	if (/^; ASM ONLY.*$/) { exit(0); }
	if (/^; STANDARD SYMBOLS.*$/) { $pre = "XV65_"; }
	elsif (/^;(.*)/) { printf "/* %-71s */\n", $1; }
	elsif (/^(\S*?)\s*?=\s*\$(.*?)$/) { print "#define $1 0x$2\n"; }
	elsif (/^(\S*?)\s*?=\s*(.*?)$/) { printf "#define $pre$1 $2\n"; }
	else { print "$_\n"; }
}
