#! /usr/bin/perl

print <<END;
/*** File generated by inc2h.pl - DO NOT EDIT ***/

END
while (<>) {
	chop;
	if (/^; ASM ONLY.*$/) { exit(0); }
	elsif (/^;(.*)/) { printf "/* %-71s */\n", $1; }
	elsif (/^(\S*?)\s*?=\s*\$(.*?)$/) { print "#define $1 0x$2\n"; }
	elsif (/^(\S*?)\s*?=\s*(.*?)$/) { print "#define $1 $2\n"; }
	else { print "$_\n"; }
}
