#! /usr/bin/perl

print <<END;
/*** File generated by inc2sym.pl - DO NOT EDIT ***/

END
while (<>) {
	chop;
	if (/^([^;]\S*?)\s*?=\s*\$(.*?)$/) { print "{\"$1\",0x$2},\n"; }
	elsif (/^([^;]\S*?)\s*?=\s*(.*?)$/) { print "{\"$1\",$2},\n"; }
}
